# Generated by Django 4.2.30 on 2026-07-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
