services:
  web:
    build: ./backend
    ports:
      - "9000:8000"
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  jupyter:
    build:
      context: ./backend
      dockerfile: Dockerfile.jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./backend:/app
      - jupyter_data:/root/.jupyter
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   depends_on:
  #     - web

volumes:
  postgres_data:
  jupyter_data:
