# Generated by Django 4.2.30 on 2026-07-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_set_card_card_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='scryfall_id',
            field=models.CharField(default=1, max_length=36, unique=True),
            preserve_default=False,
        ),
    ]
