# Generated by Django 4.2.30 on 2026-07-12 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_oracle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_set',
        ),
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
        migrations.RemoveField(
            model_name='card',
            name='scryfall_id',
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scryfall_id', models.CharField(max_length=36, unique=True)),
                ('image', models.CharField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.card')),
                ('card_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.set')),
            ],
        ),
    ]
