# Generated by Django 4.2.30 on 2026-07-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_remove_card_card_set_remove_card_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['card__name', 'card_set__name']},
        ),
        migrations.AddField(
            model_name='variant',
            name='collector_number',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
