# Generated by Django 4.2.30 on 2026-07-11 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField()),
                ('name', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='card_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cards.set'),
            preserve_default=False,
        ),
    ]
