# Generated by Django 4.2.30 on 2026-07-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_scryfall_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='oracle_id',
            field=models.CharField(default=1, max_length=36),
            preserve_default=False,
        ),
    ]
