# Generated by Django 4.2.30 on 2026-07-12 04:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_variant_options_variant_collector_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='available',
            name='finish',
            field=models.CharField(choices=[('foil', 'Foil'), ('nonfoil', 'Non-Foil')], default=[], max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='finishes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('foil', 'Foil'), ('nonfoil', 'Non-Foil')], max_length=10), default=list, size=None),
        ),
    ]
