# Generated by Django 4.2.30 on 2026-07-12 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_available_finish_variant_finishes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available',
            name='card',
        ),
        migrations.AddField(
            model_name='available',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cards.variant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wanted',
            name='finish',
            field=models.CharField(choices=[('foil', 'Foil'), ('nonfoil', 'Non-Foil')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wanted',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cards.variant'),
            preserve_default=False,
        ),
    ]
