# Generated by Django 4.2.30 on 2026-07-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_remove_available_card_available_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='available',
            name='condition',
            field=models.CharField(choices=[('M', 'Mint'), ('NM', 'Near Mint')], default='NM', max_length=10),
        ),
    ]
