# Generated by Django 4.2.30 on 2026-07-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_available_user_wanted_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='available',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('CN', 'Chinese'), ('JP', 'Japanese'), ('ITA', 'Italian'), ('OTHER', 'Other')], default='EN', max_length=10),
        ),
    ]
