# Generated by Django 4.2.30 on 2026-07-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_available_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='available',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='available',
            name='condition',
            field=models.CharField(choices=[('M', 'Mint'), ('NM', 'Near Mint'), ('LP', 'Lightly Played'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played')], default='NM', max_length=10),
        ),
    ]
