# Generated by Django 4.2.30 on 2026-07-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_available_quantity_alter_available_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='back_image',
            field=models.CharField(blank=True, null=True),
        ),
    ]
