# Generated by Django 4.2.30 on 2026-07-31 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_variant_back_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanted',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cards.variant'),
        ),
    ]
