# Generated by Django 4.2.30 on 2026-07-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_alter_wanted_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanted',
            name='finish',
            field=models.CharField(blank=True, choices=[('foil', 'Foil'), ('nonfoil', 'Non-Foil')], max_length=10, null=True),
        ),
    ]
