# Generated by Django 4.2.30 on 2026-08-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_alter_wanted_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanted',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
