# Generated by Django 4.2.30 on 2026-10-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0018_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='icon_svg_uri',
            field=models.CharField(blank=True, null=True),
        ),
    ]
